### PR TITLE
Explore rearchitecting PenguinGraph's around closures.

### PR DESCRIPTION
**Pull request by saeta**
Previously, `PenguinGraph` used Visitors to allow composition of
algorithms. This worked, but was somewhat unwieldly, and had a number
of drawbacks, including:

 - All graph traversals ended up being `throw`ing, which forced users to
   smear `try`'s in their code, because there was no way to express the
   `rethrows`-ingness within a protocol.
 - Because there's no `override` checking for implementing methods on
   protocols, it was very easy to implement a subtly wrong method
   signature. This would result in your method never being called.
 - I structured the BFS Visitor to itself contain the worklist within
   itself, so that Dijkstra's algorithm could modify it. This was a
   bit of a hack.

This new design, centered around closures, improves on all of these key
shortcomings of the previous design.

Performance benchmarks
======================

Before
------
```
name                                                              time            std         iterations
--------------------------------------------------------------------------------------------------------
AdjacencyList: build a complete graph of size 10                  47989.0 ns      ±  11.83 %  29416
AdjacencyList: build a complete graph of size 100                 4374958.0 ns    ±   7.11 %  304
AdjacencyList: build a complete graph of size 1000                435099068.0 ns  ±   2.91 %  3
AdjacencyList: DFS on oneEdge graph, counting visitor             1961937.5 ns    ±  14.90 %  696
AdjacencyList: BFS on oneEdge graph, counting visitor             1692833.0 ns    ±   7.64 %  871
AdjacencyList: Dijkstra on oneEdge graph, counting visitor        3508803.0 ns    ±   5.90 %  401
AdjacencyList: DFS on twoEdges graph, counting visitor            2565233.0 ns    ±   9.24 %  547
AdjacencyList: BFS on twoEdges graph, counting visitor            2314113.0 ns    ±   7.58 %  603
AdjacencyList: Dijkstra on twoEdges graph, counting visitor       5759319.0 ns    ±   6.72 %  258
AdjacencyList: DFS on completeGraph graph, counting visitor       579625778.5 ns  ±   0.80 %  2
AdjacencyList: BFS on completeGraph graph, counting visitor       603404920.5 ns  ±   2.51 %  2
AdjacencyList: Dijkstra on completeGraph graph, counting visitor  746910440.5 ns  ±   2.56 %  2
AdjacencyList: DFS on completeDAG graph, counting visitor         288798695.0 ns  ±   3.41 %  5
AdjacencyList: BFS on completeDAG graph, counting visitor         307119093.0 ns  ±   3.92 %  5
AdjacencyList: Dijkstra on completeDAG graph, counting visitor    289096968.0 ns  ±   2.94 %  5
AdjacencyList: Topological sort on completeDAG                    291341816.0 ns  ±   3.42 %  5
```

After
-----

```
name                                                              time            std         iterations
--------------------------------------------------------------------------------------------------------
AdjacencyList: build a complete graph of size 10                  48667.0 ns      ±  12.87 %  28688
AdjacencyList: build a complete graph of size 100                 4460344.0 ns    ±   7.61 %  326
AdjacencyList: build a complete graph of size 1000                449588758.0 ns  ±   2.48 %  3
AdjacencyList: DFS on oneEdge graph, counting visitor             1906472.0 ns    ±   8.44 %  727
AdjacencyList: BFS on oneEdge graph, counting visitor             1546362.0 ns    ±   8.32 %  915
AdjacencyList: Dijkstra on oneEdge graph, counting visitor        4079355.0 ns    ±  11.06 %  335
AdjacencyList: DFS on twoEdges graph, counting visitor            2691643.0 ns    ±   8.99 %  521
AdjacencyList: BFS on twoEdges graph, counting visitor            2097564.5 ns    ±   7.12 %  646
AdjacencyList: Dijkstra on twoEdges graph, counting visitor       5804325.5 ns    ±   8.40 %  240
AdjacencyList: DFS on completeGraph graph, counting visitor       597149572.5 ns  ±   1.36 %  2
AdjacencyList: BFS on completeGraph graph, counting visitor       646528025.5 ns  ±   0.66 %  2
AdjacencyList: Dijkstra on completeGraph graph, counting visitor  950868232.5 ns  ±   1.62 %  2
AdjacencyList: DFS on completeDAG graph, counting visitor         308286970.0 ns  ±   2.56 %  4
AdjacencyList: BFS on completeDAG graph, counting visitor         305959304.0 ns  ±   2.41 %  4
AdjacencyList: Dijkstra on completeDAG graph, counting visitor    404302281.0 ns  ±   2.67 %  3
AdjacencyList: Topological sort on completeDAG                    341198802.5 ns  ±   1.93 %  4
```

PAIR=@dabrahams

### CODE REVIEW

**Comment by saeta** [comment]
Running with cross module optimizations:

```
saeta-macbookpro2:penguin saeta$ time swift run -c release -Xswiftc -cross-module-optimization Benchmarks --filter "AdjacencyList"
[8/8] Linking Benchmarks
running AdjacencyList: build a complete graph of size 10... done! (2098.31 ms)
running AdjacencyList: build a complete graph of size 100... done! (1753.17 ms)
running AdjacencyList: build a complete graph of size 1000... done! (2229.53 ms)
running AdjacencyList: DFS on oneEdge graph, counting visitor... done! (1935.39 ms)
running AdjacencyList: BFS on oneEdge graph, counting visitor... done! (1570.37 ms)
running AdjacencyList: Dijkstra on oneEdge graph, counting visitor... done! (1467.91 ms)
running AdjacencyList: DFS on twoEdges graph, counting visitor... done! (1888.60 ms)
running AdjacencyList: BFS on twoEdges graph, counting visitor... done! (1414.69 ms)
running AdjacencyList: Dijkstra on twoEdges graph, counting visitor... done! (1665.24 ms)
running AdjacencyList: DFS on completeGraph graph, counting visitor... done! (1984.40 ms)
running AdjacencyList: BFS on completeGraph graph, counting visitor... done! (1853.46 ms)
running AdjacencyList: Dijkstra on completeGraph graph, counting visitor... done! (1866.28 ms)
running AdjacencyList: DFS on completeDAG graph, counting visitor... done! (1557.72 ms)
running AdjacencyList: BFS on completeDAG graph, counting visitor... done! (1522.68 ms)
running AdjacencyList: Dijkstra on completeDAG graph, counting visitor... done! (1496.76 ms)
running AdjacencyList: Topological sort on completeDAG... done! (1580.36 ms)

name                                                              time           std         iterations  
-------------------------------------------------------------------------------------------------------
AdjacencyList: build a complete graph of size 10                  5554.0 ns      ±  34.39 %  249576      
AdjacencyList: build a complete graph of size 100                 171107.5 ns    ±  22.58 %  9026        
AdjacencyList: build a complete graph of size 1000                6914846.5 ns   ±  14.53 %  200         
AdjacencyList: DFS on oneEdge graph, counting visitor             48011.0 ns     ±  21.12 %  26925       
AdjacencyList: BFS on oneEdge graph, counting visitor             120977.0 ns    ±  17.93 %  11454       
AdjacencyList: Dijkstra on oneEdge graph, counting visitor        1358657.0 ns   ±  14.60 %  938         
AdjacencyList: DFS on twoEdges graph, counting visitor            45674.0 ns     ±  13.32 %  28852       
AdjacencyList: BFS on twoEdges graph, counting visitor            118505.0 ns    ±  15.34 %  10396       
AdjacencyList: Dijkstra on twoEdges graph, counting visitor       2134791.0 ns   ±   9.61 %  652         
AdjacencyList: DFS on completeGraph graph, counting visitor       4471161.0 ns   ±  11.35 %  329         
AdjacencyList: BFS on completeGraph graph, counting visitor       3733026.0 ns   ±  10.44 %  379         
AdjacencyList: Dijkstra on completeGraph graph, counting visitor  41664100.0 ns  ±   5.50 %  34          
AdjacencyList: DFS on completeDAG graph, counting visitor         2139480.5 ns   ±  10.38 %  592         
AdjacencyList: BFS on completeDAG graph, counting visitor         1730760.0 ns   ±   8.03 %  751         
AdjacencyList: Dijkstra on completeDAG graph, counting visitor    18267805.0 ns  ±   4.34 %  69          
AdjacencyList: Topological sort on completeDAG                    1964697.5 ns   ±   7.75 %  678         
```

**Comment by shabalind** [comment]
@saeta Can you please provide updated before numbers with cross module optimisations? Otherwise it's hard to compare apples-to-apples.

**Comment by saeta** [comment]
Before performance with cross-module optimization:

```
saeta-macbookpro2:penguin saeta$ time swift run -c release -Xswiftc -cross-module-optimization Benchmarks --filter "AdjacencyList"
[5/5] Linking Benchmarks
running AdjacencyList: build a complete graph of size 10... done! (2127.44 ms)
running AdjacencyList: build a complete graph of size 100... done! (1599.99 ms)
running AdjacencyList: build a complete graph of size 1000... done! (2220.43 ms)
running AdjacencyList: DFS on oneEdge graph, counting visitor... done! (1929.94 ms)
running AdjacencyList: BFS on oneEdge graph, counting visitor... done! (1533.87 ms)
running AdjacencyList: Dijkstra on oneEdge graph, counting visitor... done! (1692.78 ms)
running AdjacencyList: DFS on twoEdges graph, counting visitor... done! (1972.04 ms)
running AdjacencyList: BFS on twoEdges graph, counting visitor... done! (1607.99 ms)
running AdjacencyList: Dijkstra on twoEdges graph, counting visitor... done! (1794.17 ms)
running AdjacencyList: DFS on completeGraph graph, counting visitor... done! (1966.21 ms)
running AdjacencyList: BFS on completeGraph graph, counting visitor... done! (1892.94 ms)
running AdjacencyList: Dijkstra on completeGraph graph, counting visitor... done! (1593.83 ms)
running AdjacencyList: DFS on completeDAG graph, counting visitor... done! (1658.09 ms)
running AdjacencyList: BFS on completeDAG graph, counting visitor... done! (1743.82 ms)
running AdjacencyList: Dijkstra on completeDAG graph, counting visitor... done! (1522.51 ms)
running AdjacencyList: Topological sort on completeDAG... done! (2121.70 ms)

name                                                              time            std         iterations  
--------------------------------------------------------------------------------------------------------
AdjacencyList: build a complete graph of size 10                  5839.0 ns       ±  30.13 %  245335      
AdjacencyList: build a complete graph of size 100                 159163.5 ns     ±   9.07 %  8906        
AdjacencyList: build a complete graph of size 1000                7106856.0 ns    ±   9.43 %  193         
AdjacencyList: DFS on oneEdge graph, counting visitor             43573.0 ns      ±  23.82 %  30262       
AdjacencyList: BFS on oneEdge graph, counting visitor             121771.0 ns     ±  12.10 %  11448       
AdjacencyList: Dijkstra on oneEdge graph, counting visitor        2561238.0 ns    ±  12.26 %  527         
AdjacencyList: DFS on twoEdges graph, counting visitor            45764.0 ns      ±  21.69 %  29197       
AdjacencyList: BFS on twoEdges graph, counting visitor            128229.5 ns     ±  13.70 %  11248       
AdjacencyList: Dijkstra on twoEdges graph, counting visitor       3817870.0 ns    ±  11.35 %  343         
AdjacencyList: DFS on completeGraph graph, counting visitor       4968374.0 ns    ±   6.66 %  281         
AdjacencyList: BFS on completeGraph graph, counting visitor       4551877.0 ns    ±   7.18 %  299         
AdjacencyList: Dijkstra on completeGraph graph, counting visitor  199448098.0 ns  ±   4.48 %  7           
AdjacencyList: DFS on completeDAG graph, counting visitor         2560007.0 ns    ±   7.13 %  531         
AdjacencyList: BFS on completeDAG graph, counting visitor         2409217.0 ns    ±  11.84 %  597         
AdjacencyList: Dijkstra on completeDAG graph, counting visitor    13304499.5 ns   ±   8.72 %  102         
AdjacencyList: Topological sort on completeDAG                    6581876.5 ns    ±   9.06 %  208         

real	0m37.559s
user	0m37.372s
sys	0m0.800s
```

**Comment by saeta** [comment]
While I haven't done any profiling, the numbers above indicate that this new closure-based design is generally slightly faster. Based on the design discussion earlier, I'll go ahead and polish this up and get this merged in.

**Comment by shabalind** [comment]
@saeta Glad to see that we make decisions on empirical numbers easily now! :)

**Pull request merged**
