### PR TITLE
Regenerate all docs

### PR DESCRIPTION
**Pull request by texasmichelle**
Change jazzy configs to point to `main`.
Update jazzy config to reflect the move to `PenguinTables` in #78 .
Regenerate all docs to match.

### CODE REVIEW

**Comment by saeta** [comment]
Thank you @texasmichelle !!!

**Comment by dabrahams** [comment]
Where are the docs visible, though?  There's no GH pages site where the homepage links point.

**Comment by texasmichelle** [comment]
@saeta Are you able to point the gh-pages target to the `main` branch? [This doc](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) looks relevant.

**Comment by texasmichelle** [comment]
public URLs are now working @dabrahams

**Comment by dabrahams** [comment]
Nice!  Now, @saeta, how about we get the generated HTML out of this repo?  Even if you need to check it in somewhere else, just trying to quick-open a swift file, or do a global search, often leaves me in an .html file I don't care about.  Slows development down a lot!

**Pull request merged**
